### ISSUE TITLE
error when training

### ISSUE THREAD

**Issue by jingyj203** [rongchengtu1/UHSCM#4]
Traceback (most recent call last):
  File "UHSCM.py", line 231, in <module>
    UHSCM_algo(opt)
  File "UHSCM.py", line 152, in UHSCM_algo
    probs = (image_label_probs > 0.5).float()
UnboundLocalError: local variable 'image_label_probs' referenced before assignment

**Comment by jingyj203** [comment]
I change the code as follwing:
         probs = (image_label_probs > 0.5).float()
        image_label_probs = F.normalize(torch.tensor(image_label_probs).float())
TO:
        #probs = (image_label_probs > 0.5).float()
        #image_label_probs = F.normalize(torch.tensor(image_label_probs).float())


it works ,but i meet the new issue:

[Train Phase][Epoch:   1/ 60][Loss: 1.11079][Lossc: 17.13326][Lossr: 3.52278]
Traceback (most recent call last):
  File "UHSCM.py", line 231, in <module>
    UHSCM_algo(opt)
  File "UHSCM.py", line 195, in UHSCM_algo
    optimizer = AdjustLearningRate(optimizer, epoch, learning_rate_i)
NameError: name 'AdjustLearningRate' is not defined

should i? : #optimizer = AdjustLearningRate(optimizer, epoch, learning_rate_i)
Is this change of code right?
